### ISSUE TITLE
Please include assignment problem statements

### ISSUE THREAD

**Issue by aniketp** [APwhitehat/NumericalMethods#2]
I take it that these are the course assignments. Could you please also include all the assignment problems (They're usually PDFs right?) too?
That would be really helpful!

**Comment by APwhitehat** [comment]
Assignments PDFs generally defined the input & output of the programs. Which is handled by the main function. Classes can be used universally but main function would change assignment to assignment.
So it's better not to upload the assignments. 
But more seriously they aren't mine to share.

**Comment by aniketp** [comment]
Cool, no issues.
